trigger:
- main

pool:
  name: oal  # Usamos el pool autohospedado

steps:
# 1. Configurar Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

# 2. Instalar dependencias y construir el proyecto
- script: |
    npm install
    npm run build --prod
  displayName: 'Install dependencies and build Angular app'

# 3. Instalar Firebase CLI
- script: |
    npm install -g firebase-tools
  displayName: 'Install Firebase CLI'

# 4. Desplegar en Firebase Hosting
- script: |
    firebase deploy --token $(fisebase)
  displayName: 'Deploy to Firebase Hosting'
